# This file was generated by GoReleaser. DO NOT EDIT.
cask "oidc-cli" do
  desc "Command-line OIDC client, get a token without all the fuss"
  homepage "https://github.com/jentz/oidc-cli"
  version "0.1.18"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oidc-cli"

  on_macos do
    on_intel do
      url "https://github.com/jentz/oidc-cli/releases/download/v0.1.18/oidc-cli_Darwin_x86_64.tar.gz"
      sha256 "5d5ea03bc03d57f5db282af4fe4f09047f1f81bafec4084b898c56710df63b5b"
    end
    on_arm do
      url "https://github.com/jentz/oidc-cli/releases/download/v0.1.18/oidc-cli_Darwin_arm64.tar.gz"
      sha256 "482639263ae91a23c2a183f21fe777af3503f73ebad83d8f67cfe55924dd2f7b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jentz/oidc-cli/releases/download/v0.1.18/oidc-cli_Linux_x86_64.tar.gz"
      sha256 "7aecdd520a01aada8486583ffdbaeb0c646bf0c853beaf351fcc89414a4922e0"
    end
    on_arm do
      url "https://github.com/jentz/oidc-cli/releases/download/v0.1.18/oidc-cli_Linux_arm64.tar.gz"
      sha256 "e37d07be1b566637d9fac781c1ad43715daf1136325c97215ed7dce0b0f7f361"
    end
  end

  conflicts_with formula: [
      "oidc-cli",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oidc-cli"]
    end
  end

  # No zap stanza required
end
