# This file was generated by GoReleaser. DO NOT EDIT.
cask "oidc-cli" do
  desc "Command-line OIDC client, get a token without all the fuss"
  homepage "https://github.com/jentz/oidc-cli"
  version "0.1.17"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oidc-cli"

  on_macos do
    on_intel do
      url "https://github.com/jentz/oidc-cli/releases/download/v0.1.17/oidc-cli_Darwin_x86_64.tar.gz"
      sha256 "d4ee2ac2eeca9eb09b31288fce6a075f032d1c2c109873588b9edfa4c664bf42"
    end
    on_arm do
      url "https://github.com/jentz/oidc-cli/releases/download/v0.1.17/oidc-cli_Darwin_arm64.tar.gz"
      sha256 "67cd3ce22286758bc7b936bf5c33dfc2c64d55a39d2bf39e6e08983a7aa9a3e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jentz/oidc-cli/releases/download/v0.1.17/oidc-cli_Linux_x86_64.tar.gz"
      sha256 "e5da13a26dbd3d10273638d0c4c28741dad2b28916e58208f5d989a2e468a4a4"
    end
    on_arm do
      url "https://github.com/jentz/oidc-cli/releases/download/v0.1.17/oidc-cli_Linux_arm64.tar.gz"
      sha256 "4507a9b98450417d935e749d0a2b9d1d1066dd940ce75bc8d8321403f6535ecc"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oidc-cli"]
    end
  end

  # No zap stanza required
end
