# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OidcCli < Formula
  desc "Command-line OIDC client, get a token without all the fuss"
  homepage "https://github.com/jentz/vigilant-dollop"
  version "0.1.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jentz/vigilant-dollop/releases/download/v0.1.6/vigilant-dollop_Darwin_x86_64.tar.gz"
      sha256 "f664f18340669e3d13571be7a3a825d5a33239a7f9753f44b9adf24dad35f4e4"

      def install
        bin.install "oidc-cli"
      end
    end
    on_arm do
      url "https://github.com/jentz/vigilant-dollop/releases/download/v0.1.6/vigilant-dollop_Darwin_arm64.tar.gz"
      sha256 "ed288c48da337440b403af00bf82783db2b24e7b4537a3031de1b745e1b77bcd"

      def install
        bin.install "oidc-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jentz/vigilant-dollop/releases/download/v0.1.6/vigilant-dollop_Linux_x86_64.tar.gz"
        sha256 "c3072f5801d4ee3dd9774b11615e22535f74b6fa716e6db4f876f304c0f8bc9b"

        def install
          bin.install "oidc-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jentz/vigilant-dollop/releases/download/v0.1.6/vigilant-dollop_Linux_arm64.tar.gz"
        sha256 "e8c75fcdb94ee9ba95d08fa76ef6647cf80846a59caf4af526979c4dcc23725d"

        def install
          bin.install "oidc-cli"
        end
      end
    end
  end
end
